name = "rdr-ist"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "MEDYA"
bucket_name = "rdr-ist-medya"

[[kv_namespaces]]
binding = "HABERLER"
id = "cmp6vldho000210g6tt26pvc5"
